# -*- coding: utf-8 -*-
"""PYTHON REVISION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yxfAEu69SFcPLCwum9eJR_5lLvJCTRd
"""

print("HELLO WORLD")
a = 27
b = 65
print("a+b")
print( a+b)
print(type(a))
str1 = "KOMALKUMARI "
print(str1*7)
Lst1 = [1,2,3,4,5,6,7]
print(Lst1)
Lst1 [4] = 9
print (Lst1)
tup1 = (27 , 14 , 3 , 29 , 10 ,)
print(tup1)
print(type(tup1))
print(type(Lst1))
print(type(str1))
dict1 = { 1:"Komal", 2:"Kajal" , 3:"Prince", 4:"Nitu" }
print("HELLO WORLD")
a = 27
b = 65
print("a+b")
print( a+b)
print(type(a))
str1 = "KOMALKUMARI "
print(str1*7)
Lst1 = [1,2,3,4,5,6,7]
print(Lst1)
Lst1 [4] = 9
print (Lst1)
tup1 = (27 , 14 , 3 , 29 , 10 ,)
print(tup1)
print(type(tup1))
print(type(Lst1))
print(type(str1))
dict1 = { 1:"Komal", 2:"Kajal" , 3:"Prince", 4:"Nitu" }
print(dict1)
print(type(dict1))
dict1 [5] = "Devanand"
print(dict1)
# Check if a number is even or odd using if-else
num = 27
if num % 2 == 0:
    print(num, "is even")
else:
    print(num, "is odd")

# FOR loop: Print numbers from 1 to 10, skipping 5
for i in range(1, 11):
    if i == 5:
        continue  # skips 5
    print("Current number (for loop):", i)

# WHILE loop: Print numbers from 1 to 5, stop if number is 4
i = 1
while i <= 5:
    if i == 4:
        print("Stopping at 4")
        break  # exits loop when i == 4
    print("Current number (while loop):", i)
    i += 1

# if-elif-else: Grade system example
marks = 76
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 60:
    print("Grade: C")
else:
    print("Grade: Fail")

def greet(name):
    return f"Hello, {name}"
print(greet("Komal"))


try:
    x = 1 / 0
except ZeroDivisionError:
    print("Can't divide by zero!")